Lapack
erlef/blas pull request #4
Opened 2023-08-06 15:47 UTC by tanguyl

Release of BLAS 1.1. Adds:
 - support of LAPACK
 - support of the GRISP platform

2023-08-22 13:52 UTC, ziopio commented on rebar.config
> +  ]}.
This pre and post hooks are not compatible with the `grisp` plugins deployment procedure.
To use blas in a grisp project one must remove this hooks. 
Otherwise it will fails since cblas.h is not present.

2023-09-01 08:05 UTC, tanguyl reviewed
All seems good.

2023-09-01 08:06 UTC, ziopio approved these changes

2023-09-01 08:08 UTC, ziopio commented
> All seems good.

we need approval from someone inside erlef organization @peerst , i do not have the rights to merge.

2023-09-01 13:20 UTC, ziopio requested changes

2023-09-01 13:20 UTC, ziopio commented on rebar.config
> +  ]}.
@tanguyl  these hooks are still there! With these the deploy crashes.

2023-09-01 13:26 UTC, ziopio commented
> All seems good.

@tanguyl I still see the pre and post hooks in rebar.config

2025-07-17 10:31 UTC, ziopio approved these changes
This has been successfully tested on grisp2, it can be merged.

2025-07-17 10:40 UTC, peerst approved these changes
Tested and works on GRiSP

2025-07-17 10:41 UTC, merged